"use client";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { SessionProvider } from "next-auth/react";
import { ReduxProvider } from "@/lib/providers/ReduxProvider";
import { CustomProvider } from "@/lib/providers/CustomProvider";
import { usePathname } from "next/navigation";
import { Toaster } from "react-hot-toast";
import Sidebar from "@/components/Sidebar";
import LocalProvider from "@/lib/providers/LocalProvider";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-Poppins",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${popins.className}`}>
        <ReduxProvider>
          <SessionProvider>
            <CustomProvider>
              <LocalProvider>
                {pathname !== "/login" &&
                  pathname !== "/sign-up" &&
                  pathname !== "/verification" && <Header />}
                <main
                  className={`max-w-7xl mx-auto h-screen ${
                    pathname?.includes("admin") && "flex flex-col md:flex-row"
                  }`}
                >
                  {pathname?.includes("admin") && <Sidebar />}

                  {children}
                  <Toaster position="top-center" reverseOrder={false} />
                </main>
              </LocalProvider>
            </CustomProvider>
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
