"use client";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { SessionProvider } from "next-auth/react";
import { ReduxProvider } from "@/lib/providers/ReduxProvider";
import { CustomProvider } from "@/lib/providers/CustomProvider";
import { usePathname } from "next/navigation";
import { Toaster } from "react-hot-toast";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-Poppins",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${popins.className}`}>
        <ReduxProvider>
          <SessionProvider>
            <CustomProvider>
              {pathname !== "/login" && pathname !== "/sign-up" && pathname !== "/verification" && <Header />}
              {children}
              <Toaster position="top-center" reverseOrder={false} />
            </CustomProvider>
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
